import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import BgImageSection from "@/sections/BgImageSection";

const inter = Inter({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <BgImageSection/>
        
        
        
        {children}


      <Footer/>
      </body>
    </html>
  );
}
