import type { Metadata } from "next";
import {  Work_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import TestimonialSection from "@/sections/Testimonial";

const roboto = Work_Sans({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={roboto.className}>
        <div className="container bg-no-repeat bg-cover bg-center rounded-md h-[60vh] md:h-[100vh]" style={{ backgroundImage: `url(images/jugyahbg.png)` }}></div>
        <Navbar />
        
        
        {children}
        <TestimonialSection />

      <Footer/>
      </body>
    </html>
  );
}
